export const FETCH_PAGE_DATA_SUCCESS = "FETCH_PAGE_DATA_SUCCESS";
export const FETCH_PAGE_DATA_PENDING = "FETCH_PAGE_DATA_PENDING";
export const FETCH_PAGE_DATA_FAILED = "FETCH_PAGE_DATA_FAILED";
export const PAGE_RATED = "PAGE_RATED";
export const PAGE_FAVORITED = "PAGE_FAVORITED";
export const FETCH_ATTACH_FILES = "FETCH_ATTACH_FILES";
export const SUBSCRIBE = "SUBSCRIBE";
