export const CHANGE_PAGE = "CHANGE_PAGE";
export const FETCH_READ_LATER_PAGES_SUCCESS = "FETCH_READ_LATER_PAGES_SUCCESS";
export const FILTER_BY = "FILTER_BY";
export const SORT_BY = "SORT_BY";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const SELECT_PAGE = "SELECT_PAGE";
export const EMPTY_LIST = "EMPTY_LIST";
export const REMOVE_PAGES = "REMOVE_PAGES";
