-- CREATE TAGS TABLE
CREATE TABLE IF NOT EXISTS tags (
  id SERIAL PRIMARY KEY,
  page_id INT NOT NULL,
  name VARCHAR(200) NOT NULL,
  CONSTRAINT fk_page FOREIGN KEY (page_id) REFERENCES pages(id)
);