-- CREATE VIEWS TABLE
CREATE TABLE IF NOT EXISTS views (
  id SERIAL PRIMARY KEY,
  user_id INT DEFAULT NULL,
  ip VARCHAR(100) DEFAULT NULL,
  page_id INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_page FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE
);
